runmode: debug               # 开发模式, debug, release, test 部署时环境变量覆盖
addr: :2022                 # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:2022   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
jwt_secret: MuxiFresh
log:
  writers: file,stdout # 部署时输出到 stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:  # DB 配置 部署时环境变量覆盖
  name: MuxiFresh
  addr: localhost:3306
  username: root
  password: root&1234
#redis:
 # addr: 127.0.0.1:6379
  #password: ""
oss:
  access_key: 0bNiwJGpdwmvvuVAzLDjM6gnxj9MiwmSagVpIW81
  secret_key: zHA9w8PoSfL6D4dvWNwU2GF4XHUn9MalynbANE3_
  bucket_name: muxi-fresh-test
  domain_name: ossfresh-test.muxixyz.com # CDN 域名
token:
  expired: 30

